# Vectorized Operations and Broadcasting

In [1]:
import numpy as np

without Numpy

In [2]:
marks=[85,72,45,91,60]
sc_marks=[]
for mark in marks:
     sc_marks.append(mark/100)

print(sc_marks)

[0.85, 0.72, 0.45, 0.91, 0.6]


With numpy

In [3]:
marks=np.array(marks)
sc_marks=marks/100
print(sc_marks)

[0.85 0.72 0.45 0.91 0.6 ]


## Element Wise Arithmetic

In [4]:
import numpy as np
marks = np.array([85, 72, 45, 91, 60])
print(marks + 5)
print(marks - 10)
print(marks * 2)
print(marks / 100)

[90 77 50 96 65]
[75 62 35 81 50]
[170 144  90 182 120]
[0.85 0.72 0.45 0.91 0.6 ]


## Vectorised Operation on 2d Dataset

In [7]:
students = np.array([
    [85, 90, 5],
    [72, 80, 4],
    [45, 70, 3],
    [91, 95, 6],
    [60, 78, 2]
])
print(students)

[[85 90  5]
 [72 80  4]
 [45 70  3]
 [91 95  6]
 [60 78  2]]


In [8]:
sc_marks=students/100
print(sc_marks)

[[0.85 0.9  0.05]
 [0.72 0.8  0.04]
 [0.45 0.7  0.03]
 [0.91 0.95 0.06]
 [0.6  0.78 0.02]]


## Column wise scaling

In [9]:
marks = students[:, 0]
attendance = students[:, 1]
study_hours = students[:, 2]

scaled_marks = marks / 100
scaled_attendance = attendance / 100
scaled_study_hours = study_hours / 10

print("Scaled Marks:", scaled_marks)
print("Scaled Attendance:", scaled_attendance)
print("Scaled Study Hours:", scaled_study_hours)

Scaled Marks: [0.85 0.72 0.45 0.91 0.6 ]
Scaled Attendance: [0.9  0.8  0.7  0.95 0.78]
Scaled Study Hours: [0.5 0.4 0.3 0.6 0.2]


## Broadcasting

In [10]:
marks=np.array([85,72,45,91,60])
bonus=marks+5
print(bonus)

[90 77 50 96 65]


## Broadcasting with 2D array with 1D arrays

In [11]:
students = np.array([
    [85, 90, 5],
    [72, 80, 4],
    [45, 70, 3],
    [91, 95, 6],
    [60, 78, 2]
])
scale_values = np.array([100, 100, 10])
scaled_students = students / scale_values
print(scaled_students)

[[0.85 0.9  0.5 ]
 [0.72 0.8  0.4 ]
 [0.45 0.7  0.3 ]
 [0.91 0.95 0.6 ]
 [0.6  0.78 0.2 ]]


In [14]:
print(students.shape)
print(scale_values.shape)

(5, 3)
(3,)


## Add weights to features.

In [15]:
wgt=np.array([0.5,0.3,0.2])
weighted_students=scaled_students*wgt
print(weighted_students)

[[0.425 0.27  0.1  ]
 [0.36  0.24  0.08 ]
 [0.225 0.21  0.06 ]
 [0.455 0.285 0.12 ]
 [0.3   0.234 0.04 ]]


## Calculate final score

In [17]:
final_scores = np.sum(weighted_students, axis=1)
print(final_scores)

[0.795 0.68  0.495 0.86  0.574]


In [18]:
excellent = final_scores >= 0.75
print(excellent)

[ True False False  True False]


## Common Errors

### Error 1 :


In [19]:
students = np.array([
    [85, 90, 5],
    [72, 80, 4]
])

scale_values = np.array([100, 100])

scaled = students / scale_values

ValueError: operands could not be broadcast together with shapes (2,3) (2,) 

### Error 3: Using List instead of Numpy array

In [22]:
marks = [85, 72, 45]
print(marks / 100)

TypeError: unsupported operand type(s) for /: 'list' and 'int'