# NumPy Introduction + Arrays

## Install NumPy

In [1]:
!pip install numpy

Normal Code

In [2]:
features = [5.1, 3.5, 1.4, 0.2]
print(features)

[5.1, 3.5, 1.4, 0.2]


Using numPy

In [3]:
import numpy as np
feature=np.array([5.1, 3.5, 1.4, 0.2])
print(feature)

[5.1 3.5 1.4 0.2]


To check the Installation

In [4]:
import numpy as np
print(np.__version__)

2.4.6


## Creation of NumPy Array

In [5]:
arr=np.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


## Difference Between Python List and NumPy Array

### Python List

In [6]:
marks=[10,20,30]
print(marks*2)

[10, 20, 30, 10, 20, 30]


### NumPy Array

In [7]:
marks=np.array([10,20,30])
print(marks*2)

[20 40 60]


## Creation- of 2D Array

In [8]:
datasets=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(datasets)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


## Creation of 3D Array

In [9]:
image=np.array([
     [[1,2,3],[4,5,6],[7,8,9]],
     [[10,11,12],[13,14,15],[16,17,18]],
     [[19,20,21],[22,23,24],[25,26,27]]
])
print(image)

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]]


## Checking Arrays Dimensions

In [10]:
arr1=np.array([1,2,3])
arr2=np.array([[4,5,6],[7,8,9]])
print(arr1.ndim)
print(arr2.ndim)

1
2


### Checking Shape

In [11]:
dataset = np.array([
    [85, 90, 78],
    [70, 88, 92],
    [60, 75, 80]
])

print(dataset.shape)

(3, 3)


### Checking Size

In [12]:
dataset = np.array([
    [85, 90, 78],
    [70, 88, 92],
    [60, 75, 80]
])

print(dataset.size)

9


## Checking Data Type]

In [13]:
arr = np.array([10, 20, 30])
print(arr.dtype)

int64


## Creating Special Arrays

### Array of Zeros

In [14]:
zero=np.zeros(5)
print(zero)

[0. 0. 0. 0. 0.]


### Arrays of ones

In [15]:
one=np.ones((2,3))
print(one)

[[1. 1. 1.]
 [1. 1. 1.]]


### 2d Zeros Array

In [16]:
zero_2d=np.zeros((3,4))
print(zero_2d)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


### Range Array

In [17]:
arr=np.arange(1,10)
print(arr)

[1 2 3 4 5 6 7 8 9]


### Range With Step

In [18]:
arr2=np.arange(0,20,3)
print(arr2)

[ 0  3  6  9 12 15 18]


### Evenly spaced Values

In [19]:
value=np.linspace(0,1,5)
print(value)

[0.   0.25 0.5  0.75 1.  ]


## Basic Mathematical Operation

In [20]:
arr3 = np.array([10, 20, 30])

print(arr3 + 5)
print(arr3 - 5)
print(arr3 * 2)
print(arr3 / 2)

[15 25 35]
[ 5 15 25]
[20 40 60]
[ 5. 10. 15.]


## 15. AI/ML Example : Normalize Marks

In [21]:
marks=np.array([10,20,30,40,50,60,70,80,90,100])
norm=marks/100
print(norm)

[0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1. ]
