# 05_numpy_indexing_slicing

In [1]:
import numpy as np

### Indexing

In [2]:
arr=np.array([1,2,3,4,5])
for i in range(arr.size):
    print("At index",i,":",arr[i])

At index 0 : 1
At index 1 : 2
At index 2 : 3
At index 3 : 4
At index 4 : 5


### Negative Indexing

In [3]:
arr=np.array([10,20,30,40,50])
for i in range((-arr.size),0):
    print("At index",i,":",arr[i])

At index -5 : 10
At index -4 : 20
At index -3 : 30
At index -2 : 40
At index -1 : 50


### Slicing in NumPy

In [4]:
arr = np.array([10, 20, 30, 40, 50])
print(arr[1:4])

[20 30 40]


## Common Slicing Example

In [5]:
arr = np.array([10, 20, 30, 40, 50])
print(arr[:3])
print(arr[2:])
print(arr[:])
print(arr[::2])

[10 20 30]
[30 40 50]
[10 20 30 40 50]
[10 30 50]


## Indexing in 2D Array

In [6]:
dataset = np.array([
    [85, 90, 78],
    [70, 88, 92],
    [60, 75, 80]
])

### Accessing the value

In [7]:
for i in range(dataset.shape[0]):
    for j in range(dataset.shape[1]):
        print("At row",i,"and column",j,":",dataset[i][j])

At row 0 and column 0 : 85
At row 0 and column 1 : 90
At row 0 and column 2 : 78
At row 1 and column 0 : 70
At row 1 and column 1 : 88
At row 1 and column 2 : 92
At row 2 and column 0 : 60
At row 2 and column 1 : 75
At row 2 and column 2 : 80


## Slicing Rows in 2D Array

In [8]:
for i in range(dataset.shape[0]):
     print("Row",i,":",dataset[i])

Row 0 : [85 90 78]
Row 1 : [70 88 92]
Row 2 : [60 75 80]


## Slicing Columns in 2D Array

In [9]:
for i in range(dataset.shape[0]):
     print("Column",i,":",dataset[:,i])

Column 0 : [85 70 60]
Column 1 : [90 88 75]
Column 2 : [78 92 80]


## Slicing Multiple ROws and Columns

In [10]:
for i in range(dataset.shape[0]):
    for j in range(dataset.shape[1]):
        print(dataset[0:i,0:j])

[]
[]
[]
[]
[[85]]
[[85 90]]
[]
[[85]
 [70]]
[[85 90]
 [70 88]]


## Use case of AI/ML

In [11]:
data = np.array([
    [85, 90, 78, 1],
    [70, 88, 92, 1],
    [35, 40, 45, 0],
    [95, 92, 88, 1]
])

X = data[:, 0:3]
y = data[:, 3]

print("Features:")
print(X)

print("Labels:")
print(y)

Features:
[[85 90 78]
 [70 88 92]
 [35 40 45]
 [95 92 88]]
Labels:
[1 1 0 1]


## Shape

In [12]:
arr = np.array([
    [10, 20, 30],
    [40, 50, 60]
])

print(arr.shape)

(2, 3)


## Reshape

In [13]:
arr = np.array([1, 2, 3, 4, 5, 6])
new_arr = arr.reshape(2, 3)
print(new_arr)

[[1 2 3]
 [4 5 6]]


### More Examples of Reshape

In [14]:
arr = np.arange(1, 13)
arr_2d = arr.reshape(3, 4)
arr_3d = arr.reshape(2, 2, 3)
print(arr_2d)
print(arr_3d)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


### Flattening Array

In [15]:
arr = np.array([
    [1, 2, 3],
    [4, 5, 6]
])
flat = arr.flatten()
print(flat)

[1 2 3 4 5 6]


### AI/Ml Use case

In [16]:
image = np.arange(1, 785)
image_2d = image.reshape(28, 28)
print(image_2d.shape)

(28, 28)


In [17]:
flat_image = image_2d.flatten()
print(flat_image.shape)

(784,)


## Common Errors and Corrections

### Error 1: Index out of index

In [ ]:
arr = np.array([10, 20, 30])
print(arr[5])

IndexError: index 5 is out of bounds for axis 0 with size 3

### Error 2: Wrong 2D Index

In [ ]:
dataset = np.array([
    [85, 90, 78],
    [70, 88, 92]
])
print(dataset[2, 1])

IndexError: index 2 is out of bounds for axis 0 with size 2

### Error 3: Invalid Reshape

In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6])
new_arr = arr.reshape(4, 2)

ValueError: cannot reshape array of size 6 into shape (4,2)

## Boolean Filtering

In [21]:
students = np.array([[100, 85, 90], [75, 80, 82], [60, 70, 65]])
marks=students[:,0]
mask=marks>=80
print(mask)

[ True False False]


## Filtering multiple Conditions

In [22]:
marks = students[:, 0]
attendance = students[:, 1]
mask = (marks >= 80) & (attendance >= 85)
selected_students = students[mask]
print(selected_students)

[[100  85  90]]
