# Practice Tasks

In [1]:
import numpy as np

## Task 1
Create a NumPy array:
```
[10, 20, 30, 40, 50]
```
Print:
```
Array
Dimension
Shape
Size
Data type


In [3]:
arr=np.array([10,20,30,40,50])
print("Array",arr)
print("Dimension",arr.ndim)
print("Shape",arr.shape)
print("Size",arr.size)
print("Data type",arr.dtype)

Array [10 20 30 40 50]
Dimension 1
Shape (5,)
Size 5
Data type int64


## Task 2
Create a 2D NumPy array:
```
[    [85, 90, 78],    [70, 88, 92],    [60, 75, 80]]
```
Print:
```
Full dataset
Shape
Total elements


In [4]:
mat=np.array([
     [85,90,78],
     [70,88,92],
     [60,75,80]
])
print("Dataset:\n",mat)
print("Shape:",mat.shape)
print("Total elements:",mat.size)

Dataset:
 [[85 90 78]
 [70 88 92]
 [60 75 80]]
Shape: (3, 3)
Total elements: 9


## Task 3
Create:
```
Array of 5 zeros
Array of 5 ones
Array from 1 to 10
Array of even numbers from 2 to 20

In [6]:
zero=np.zeros(5)
print(zero)
one=np.ones(5)
print(one)
rarr=np.arange(1,10)
print(rarr)
rarr2=np.arange(2,20,2)
print(rarr2)

[0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1.]
[1 2 3 4 5 6 7 8 9]
[ 2  4  6  8 10 12 14 16 18]


## Task 4
Create marks array:
```
marks = np.array([80, 90, 70, 60, 100])
```
Print normalized marks by dividing by `100`.

In [7]:
marks = np.array([80, 90, 70, 60, 100])
norm = marks / 100
print(norm)

[0.8 0.9 0.7 0.6 1. ]


## Task 5
Create an array:
```
arr = np.array([5, 10, 15, 20])
```
Print:
```
arr + 5
arr - 5
arr * 2
arr / 5


In [8]:
arr = np.array([5, 10, 15, 20])
print(arr + 5)
print(arr - 5)
print(arr * 2)
print(arr / 5)

[10 15 20 25]
[ 0  5 10 15]
[10 20 30 40]
[1. 2. 3. 4.]
