# 05_numpy_indexing_slicing

In [36]:
import numpy as np

## Task 1
Create this array:
```
arr = np.array([10, 20, 30, 40, 50, 60])
```
Print:
```
First element.
Last element
Elements from index 1 to 4
Every second element
```

In [39]:
arr=np.array([10,20,30,40,50,60])
print("First element:",arr[0])
print("Last element:",arr[-1])
print("Elements from index 1 to 4:",arr[1:5])
print("Every 2nd element:",arr[0::2])

First element: 10
Last element: 60
Elements from index 1 to 4: [20 30 40 50]
Every 2nd element: [10 30 50]


## Task 2
Create this 2D dataset:
```
dataset = np.array([    
	[85, 90, 78],
    [70, 88, 92],
    [60, 75, 80]
])
```
Print:
```
First row
Second row
Value 88
Value 80
First column
Second column

In [40]:
dataset=np.array([
     [85,90,78],
     [70,88,92],
     [65,75,80]
])
print("Dataset:\n",dataset)
print("First row",dataset[0])
print("Second row",dataset[1])
print("value 88",dataset[1,1])
print("Value 80",dataset[2,2])
print("First coumn",dataset[:,0])
print("Second column",dataset[:,1])

Dataset:
 [[85 90 78]
 [70 88 92]
 [65 75 80]]
First row [85 90 78]
Second row [70 88 92]
value 88 88
Value 80 80
First coumn [85 70 65]
Second column [90 88 75]


## Task 3
Create this ML dataset:
```
data = np.array([    
	[85, 90, 78, 1],
    [70, 88, 92, 1],
    [35, 40, 45, 0],
    [95, 92, 88, 1]
])
```
Separate:
```
X = first 3 columns
y = last column
```
Print both.

In [42]:
data = np.array([    
	[85, 90, 78, 1],
    [70, 88, 92, 1],
    [35, 40, 45, 0],
    [95, 92, 88, 1]
])
x=data[:,0:3]
y=data[:,3]
print(x)
print(y)

[[85 90 78]
 [70 88 92]
 [35 40 45]
 [95 92 88]]
[1 1 0 1]


## Task 4
Create array from 1 to 12.
Convert it into:
```
3 rows and 4 columns
2 rows and 6 columns


In [45]:
arr=np.arange(1,13)
reshape_arr1=arr.reshape(3,4)
reshape_arr2=arr.reshape(2,6)
print("Original array:",arr)
print("Reshaped array (3,4):\n",reshape_arr1)
print("Reshaped array (2,6):\n",reshape_arr2)

Original array: [ 1  2  3  4  5  6  7  8  9 10 11 12]
Reshaped array (3,4):
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Reshaped array (2,6):
 [[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


## Task 5
Create a 2D array and flatten it into 1D.

In [47]:
matrix=np.array([[1,2,3],[4,5,6],[7,8,9]])
print("Original matrix:\n",matrix)
flat_mat=matrix.flatten()
print("Flattened matrix:",flat_mat)

Original matrix:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Flattened matrix: [1 2 3 4 5 6 7 8 9]
