# Feature Scaling: Standardization and Normalization

In [1]:
!pip install numpy pandas matplotlib seaborn scikit-learn

In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
data={
     "cgpa": [8.5, 6.2, 7.8, 5.9, 9.1, 8.0],
    "attendance": [85, 45, 78, 55, 95, 88],
    "previous_score": [82, 45, 76, 50, 95, 88],
    "practice_questions": [120, 30, 90, 25, 150, 110],
    "final_marks": [85, 48, 78, 52, 96, 88]
}
df=pd.DataFrame(data)
df

,cgpa,attendance,previous_score,practice_questions,final_marks
0,8.5,85,82,120,85
1,6.2,45,45,30,48
2,7.8,78,76,90,78
3,5.9,55,50,25,52
4,9.1,95,95,150,96
5,8.0,88,88,110,88


In [5]:
X = df[["cgpa", "attendance", "previous_score", "practice_questions"]]
y = df["final_marks"]
print(X)
print(y)

   cgpa  attendance  previous_score  practice_questions
0   8.5          85              82                 120
1   6.2          45              45                  30
2   7.8          78              76                  90
3   5.9          55              50                  25
4   9.1          95              95                 150
5   8.0          88              88                 110
0    85
1    48
2    78
3    52
4    96
5    88
Name: final_marks, dtype: int64


In [8]:
df.describe().round(3)

,cgpa,attendance,previous_score,practice_questions,final_marks
count,6.000,6.000,6.000,6.000,6.000
mean,7.583,74.333,72.667,87.500,74.500
std,1.273,19.876,20.549,50.374,19.877
min,5.900,45.000,45.000,25.000,48.000
25%,6.600,60.750,56.500,45.000,58.500
50%,7.900,81.500,79.000,100.000,81.500
75%,8.375,87.250,86.500,117.500,87.250
max,9.100,95.000,95.000,150.000,96.000


In [18]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

In [21]:
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()
x_train_sc=scaler.fit_transform(X_train)
x_test_scaled=scaler.transform(X_test)
print("Scaled tarining data:")
print(x_train_sc)
print("Scaled Testing Data:")
print(x_test_scaled)

Scaled tarining data:
[[ 0.26062335  0.59538708  0.6272862   0.3595883 ]
 [ 0.08687445 -0.06615412 -0.07294026 -0.08298192]
 [ 1.21624228  1.05846592  1.03575163  1.24472875]
 [-1.56374007 -1.58769888 -1.59009758 -1.52133514]]
Scaled Testing Data:
[[ 0.69499559  0.39692472  0.27717297  0.58087342]
 [-1.30311673 -2.24924009 -1.8818586  -1.41069258]]


In [29]:
from sklearn.preprocessing import MinMaxScaler
min_max_sc=MinMaxScaler()
x_train_minmax=min_max_sc.fit_transform(X_train)
x_test_minmax=min_max_sc.transform(X_test)
print("MinMax Scaled Training Data:")
print(x_train_minmax)
print("MinMax Scaled Testing data:")
print(x_test_minmax)


MinMax Scaled Training Data:
[[0.65625    0.825      0.84444444 0.68      ]
 [0.59375    0.575      0.57777778 0.52      ]
 [1.         1.         1.         1.        ]
 [0.         0.         0.         0.        ]]
MinMax Scaled Testing data:
[[ 0.8125      0.75        0.71111111  0.76      ]
 [ 0.09375    -0.25       -0.11111111  0.04      ]]


In [30]:
import pandas as pd

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error

data = {
    "cgpa": [8.5, 6.2, 7.8, 5.9, 9.1, 8.0],
    "attendance": [85, 45, 78, 55, 95, 88],
    "previous_score": [82, 45, 76, 50, 95, 88],
    "practice_questions": [120, 30, 90, 25, 150, 110],
    "final_marks": [85, 48, 78, 52, 96, 88]
}

df = pd.DataFrame(data)

X = df[["cgpa", "attendance", "previous_score", "practice_questions"]]
y = df["final_marks"]

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

scaler = StandardScaler()

X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

model = LinearRegression()

model.fit(X_train_scaled, y_train)

y_pred = model.predict(X_test_scaled)

mae = mean_absolute_error(y_test, y_pred)

print("Actual:", y_test.values)
print("Predicted:", y_pred)
print("MAE:", mae)

Actual: [85 48]
Predicted: [84.77604578 45.4822185 ]
MAE: 1.3708678619663743
