# Matrix

In [1]:
!pip install numpy pandas

In [3]:
import numpy as np
import pandas as pd

In [4]:
A = np.array([
    [2, 4, 6],
    [1, 3, 5]
], dtype=np.float64)

print("Matrix:")
print(A)

print("Shape:", A.shape)
print("Rows:", A.shape[0])
print("Columns:", A.shape[1])
print("Total entries:", A.size)

print("Mathematical a_23:", A[1, 2])

Matrix:
[[2. 4. 6.]
 [1. 3. 5.]]
Shape: (2, 3)
Rows: 2
Columns: 3
Total entries: 6
Mathematical a_23: 5.0


In [5]:
first_row = A[0, :]
second_column = A[:, 1]

print("First row:", first_row)
print("Second column:", second_column)

First row: [2. 4. 6.]
Second column: [4. 3.]


In [6]:
first_row_2d = A[0:1, :]
second_column_2d = A[:, 1:2]

print(first_row_2d.shape)
print(second_column_2d.shape)

(1, 3)
(2, 1)


In [7]:
A = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

print(A.shape)

(2, 3)


In [8]:
A = np.array([    
	[1, 2],    
	[3, 4]])
is_square = A.shape[0] == A.shape[1]
print("Square matrix:", is_square)

Square matrix: True


In [9]:
R = np.array([[2, 5, 8]])
print(R.shape)

(1, 3)


In [10]:
C = np.array([
    [2],
    [5],
    [8]
])

print(C.shape)

(3, 1)


In [11]:
O = np.zeros((2, 3))

print(O)

[[0. 0. 0.]
 [0. 0. 0.]]


In [12]:
J = np.ones((2, 3))

print(J)

[[1. 1. 1.]
 [1. 1. 1.]]


In [13]:
values = np.array([3, 5, 7])

D = np.diag(values)

print(D)
print("Diagonal:", np.diag(D))

[[3 0 0]
 [0 5 0]
 [0 0 7]]
Diagonal: [3 5 7]


In [14]:
def is_diagonal(matrix: np.ndarray) -> bool:
    if matrix.ndim != 2:
        return False

    if matrix.shape[0] != matrix.shape[1]:
        return False

    diagonal_part = np.diag(np.diag(matrix))

    return np.array_equal(matrix, diagonal_part)


D = np.array([
    [3, 0, 0],
    [0, 5, 0],
    [0, 0, 7]
])

print(is_diagonal(D))

True


In [15]:
I = np.eye(3)

print(I)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [16]:
s=4*np.eye(3)
print(s)

[[4. 0. 0.]
 [0. 4. 0.]
 [0. 0. 4.]]


In [17]:
U = np.array([
    [2, 4, 6],
    [0, 3, 5],
    [0, 0, 7]
])

print(np.triu(U))

[[2 4 6]
 [0 3 5]
 [0 0 7]]


In [18]:
L = np.array([
    [2, 0, 0],
    [4, 3, 0],
    [6, 5, 7]
])

print(np.tril(L))

[[2 0 0]
 [4 3 0]
 [6 5 7]]


In [19]:
A = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

A_transpose = A.T

print("Original:")
print(A)
print("Shape:", A.shape)

print("\nTranspose:")
print(A_transpose)
print("Shape:", A_transpose.shape)

Original:
[[1 2 3]
 [4 5 6]]
Shape: (2, 3)

Transpose:
[[1 4]
 [2 5]
 [3 6]]
Shape: (3, 2)


In [20]:
A = np.array([
    [2.0, 4.0, 1.0],
    [4.0, 3.0, 5.0],
    [1.0, 5.0, 7.0]
])

print(np.allclose(A, A.T))

True


In [21]:
diagonal = np.diag(A)
trace = np.trace(A)

print("Diagonal:", diagonal)
print("Trace:", trace)

Diagonal: [2. 3. 7.]
Trace: 12.0


In [22]:
A = np.array([
    [2.0, 1.0],
    [3.0, 4.0]
])

determinant = np.linalg.det(A)

print("Determinant:", determinant)

Determinant: 5.000000000000001


In [23]:
A = np.array([
    [1.0, 2.0],
    [2.0, 4.0]
])

print("Rank:", np.linalg.matrix_rank(A)) 

Rank: 1


In [24]:
A = np.array([
    [1.0, 2.0],
    [3.0, 4.0]
])

print(np.linalg.matrix_rank(A))

2


In [25]:
A = np.array([
    [2.0, 0.0],
    [0.0, 4.0]
])

A_inverse = np.linalg.inv(A)

print(A_inverse)
print(A @ A_inverse)

[[0.5  0.  ]
 [0.   0.25]]
[[1. 0.]
 [0. 1.]]


In [ ]:
A = np.array([
    [1.0, 2.0],
    [2.0, 4.0]
])

inverse = np.linalg.inv(A)

LinAlgError: Singular matrix

In [27]:
A = np.array([
    [2.0, 1.0],
    [1.0, -1.0]
])

b = np.array([5.0, 1.0])

solution = np.linalg.solve(A, b)

print("x:", solution[0])
print("y:", solution[1])

x: 2.0
y: 1.0


In [28]:
print(A @ solution)
print(b)

[5. 1.]
[5. 1.]


In [29]:
X = np.array([
    [6.0, 85.0, 72.0],
    [4.0, 70.0, 65.0],
    [8.0, 92.0, 81.0]
])

ones = np.ones((X.shape[0], 1))

X_with_bias = np.hstack((ones, X))

print(X_with_bias)
print(X_with_bias.shape)

[[ 1.  6. 85. 72.]
 [ 1.  4. 70. 65.]
 [ 1.  8. 92. 81.]]
(3, 4)


In [30]:
from __future__ import annotations

import numpy as np
from numpy.typing import NDArray


def inspect_matrix(matrix: NDArray[np.float64]) -> dict[str, object]:
    if not isinstance(matrix, np.ndarray):
        raise TypeError("matrix must be a NumPy array.")

    if matrix.ndim != 2:
        raise ValueError(
            f"Expected a 2D matrix, received shape {matrix.shape}."
        )

    rows, columns = matrix.shape
    is_square = rows == columns

    report: dict[str, object] = {
        "shape": matrix.shape,
        "rows": rows,
        "columns": columns,
        "size": matrix.size,
        "dtype": str(matrix.dtype),
        "is_square": is_square,
        "rank": int(np.linalg.matrix_rank(matrix)),
        "contains_nan": bool(np.isnan(matrix).any()),
        "contains_infinity": bool(np.isinf(matrix).any())
    }

    if is_square:
        report["trace"] = float(np.trace(matrix))
        report["determinant"] = float(np.linalg.det(matrix))
        report["is_symmetric"] = bool(
            np.allclose(matrix, matrix.T)
        )
        report["is_diagonal"] = bool(
            np.allclose(matrix, np.diag(np.diag(matrix)))
        )

    return report


A = np.array([
    [2.0, 1.0],
    [1.0, 3.0]
])

report = inspect_matrix(A)

for key, value in report.items():
    print(f"{key}: {value}")

shape: (2, 2)
rows: 2
columns: 2
size: 4
dtype: float64
is_square: True
rank: 2
contains_nan: False
contains_infinity: False
trace: 5.0
determinant: 5.000000000000001
is_symmetric: True
is_diagonal: False


In [31]:
A = np.array([
    [1.0, 1.0],
    [1.0, 1.000001]
])

condition_number = np.linalg.cond(A)

print("Condition number:", condition_number)

Condition number: 4000002.0005977214


In [35]:
!pip install scipy

In [36]:
from scipy.sparse import csr_matrix

dense_matrix = np.array([
    [0, 0, 5, 0],
    [0, 3, 0, 0],
    [1, 0, 0, 0]
])

sparse_matrix = csr_matrix(dense_matrix)

print(sparse_matrix)

<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 3 stored elements and shape (3, 4)>
  Coords	Values
  (0, 2)	5
  (1, 1)	3
  (2, 0)	1
