# Why Linear Algebra Power ML

In [2]:
!pip install numpy pandas

In [3]:
import numpy as np

In [4]:
loss=np.float64(2.45)
print(loss)
print(type(loss))

2.45
<class 'numpy.float64'>


In [5]:
student = np.array([6.0, 85.0, 72.0])

print(student)
print("Shape:", student.shape)
print("Dimensions:", student.ndim)
print("Number of values:", student.size)
print("Datatype:", student.dtype)

[ 6. 85. 72.]
Shape: (3,)
Dimensions: 1
Number of values: 3
Datatype: float64


In [8]:
np.array([6, 85, 72]).shape

(3,)

In [9]:
row_vector = np.array([[6.0, 85.0, 72.0]])
print(row_vector.shape)


(1, 3)


In [10]:
column_vector = np.array([    [6.0],    [85.0],    [72.0]])
print(column_vector.shape)

(3, 1)


In [11]:
X = np.array([
    [6.0, 85.0, 72.0],
    [4.0, 70.0, 65.0],
    [8.0, 92.0, 81.0],
    [5.0, 78.0, 70.0]
])

print(X)
print("Shape:", X.shape)
print("Dimensions:", X.ndim)
print("Rows:", X.shape[0])
print("Columns:", X.shape[1])

[[ 6. 85. 72.]
 [ 4. 70. 65.]
 [ 8. 92. 81.]
 [ 5. 78. 70.]]
Shape: (4, 3)
Dimensions: 2
Rows: 4
Columns: 3


In [12]:
image_batch = np.zeros((32, 224, 224, 3))

print("Shape:", image_batch.shape)
print("Dimensions:", image_batch.ndim)
print("Total values:", image_batch.size)

Shape: (32, 224, 224, 3)
Dimensions: 4
Total values: 4816896


In [13]:
from __future__ import annotations

import numpy as np
from numpy.typing import NDArray


def create_student_vector(
    study_hours: float,
    attendance: float,
    previous_score: float
) -> NDArray[np.float64]:
    """Create a validated student feature vector."""

    if study_hours < 0:
        raise ValueError("study_hours cannot be negative.")

    if not 0 <= attendance <= 100:
        raise ValueError("attendance must be between 0 and 100.")

    if not 0 <= previous_score <= 100:
        raise ValueError("previous_score must be between 0 and 100.")

    return np.array(
        [study_hours, attendance, previous_score],
        dtype=np.float64
    )


student = create_student_vector(
    study_hours=6,
    attendance=85,
    previous_score=72
)

print(student)
print(student.shape)
print(student.dtype)

[ 6. 85. 72.]
(3,)
float64


In [14]:
from __future__ import annotations

import numpy as np
from numpy.typing import NDArray


def validate_feature_matrix(
    X: NDArray[np.float64],
    expected_features: int
) -> None:
    """Validate a two-dimensional numerical feature matrix."""

    if X.ndim != 2:
        raise ValueError(
            f"Expected a 2D feature matrix, received shape {X.shape}."
        )

    if X.shape[1] != expected_features:
        raise ValueError(
            f"Expected {expected_features} features, "
            f"received {X.shape[1]}."
        )

    if X.shape[0] == 0:
        raise ValueError("Feature matrix cannot be empty.")

    if not np.isfinite(X).all():
        raise ValueError(
            "Feature matrix contains NaN or infinite values."
        )


X = np.array([
    [6.0, 85.0, 72.0],
    [4.0, 70.0, 65.0],
    [8.0, 92.0, 81.0]
])

validate_feature_matrix(X, expected_features=3)

print("Feature matrix is valid.")

Feature matrix is valid.


In [15]:
print("First observation:")
print(X[0])

print("Study-hours column:")
print(X[:, 0])

print("Attendance column:")
print(X[:, 1])

print("Previous-score column:")
print(X[:, 2])

First observation:
[ 6. 85. 72.]
Study-hours column:
[6. 4. 8.]
Attendance column:
[85. 70. 92.]
Previous-score column:
[72. 65. 81.]


In [16]:
dataset = np.array([    
	[6.0, 85.0, 72.0, 78.0],    
	[4.0, 70.0, 65.0, 67.0],    
	[8.0, 92.0, 81.0, 88.0],    
	[5.0, 78.0, 70.0, 73.0]
])
X = dataset[:, :-1]
y = dataset[:, -1]
print("X shape:", X.shape)
print("y shape:", y.shape)
print("\nFeatures:")
print(X)
print("\nTarget:")
print(y)

X shape: (4, 3)
y shape: (4,)

Features:
[[ 6. 85. 72.]
 [ 4. 70. 65.]
 [ 8. 92. 81.]
 [ 5. 78. 70.]]

Target:
[78. 67. 88. 73.]
